spring:
  application:
    name: rest-with-spring-boot-java-and-erudio
  datasource:
      driver-class-name: com.mysql.jc.jdbc.driver
      url: jdbc:mysql://localhost:3306/rest_with_spring_boot_java_erudio?useTimezone=true&serverTimezone=UTC
      username: root
      password: Co123456789
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false